Updates for Convenience
Extrct/react-native-stars pull request #2
Opened 2017-08-29 22:13 UTC by gaboelnuevo

* Add disabled prop
* Add images by default
* Tint Color prop for images

2017-09-03 20:39 UTC, 4umo requested changes

2017-09-03 20:39 UTC, Extrct commented on README.md
> +|**`disabled`**|bool|Disable edition|No|`false`|
change the description to 'Disables onPress/buttons in Selection mode'

2017-09-03 20:39 UTC, Extrct commented on index.js
> +          <Image style={[{width: this.props.starSize, height: this.props.starSize}, {tintColor: this.props.tintColor}]} source={starImg} />
Is there reason why this needs style array syntax? I'm not too familiar with its use but I'm wondering what it adds here.

2017-09-05 18:04 UTC, gaboelnuevo reviewed
Updated!

2017-09-06 21:07 UTC, 4umo approved these changes
looks good, thanks :)

2017-09-06 21:07 UTC, merged